import { ParticleSystem } from '../core/ParticleSystem.js';
export declare class WebGLRenderer {
    private canvas;
    private gl;
    private particleProgram;
    private trailProgram;
    private trailRenderer;
    private particleVertexBuffer;
    private particleColorBuffer;
    private particleSizeBuffer;
    private particleAlphaBuffer;
    private trailVertexBuffer;
    private trailColorBuffer;
    private trailAlphaBuffer;
    private particleTransformUniform;
    private particlePointSizeUniform;
    private particleGlowIntensityUniform;
    private trailTransformUniform;
    constructor(canvas: HTMLCanvasElement);
    private initializeWebGL;
    private initializeShaders;
    private createShader;
    private createProgram;
    private initializeBuffers;
    private setupWebGLState;
    render(particleSystem: ParticleSystem): void;
    private renderTrails;
    private renderParticles;
    resize(width: number, height: number): void;
}
